"""Add image column to doctor table

Revision ID: fcbfb8b7184f
Revises: 852b7f8bfe53
Create Date: 2025-10-20 14:44:28.981071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbfb8b7184f'
down_revision: Union[str, Sequence[str], None] = '852b7f8bfe53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chambers_address_trgm'), table_name='chambers', postgresql_ops={'address': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_visiting_hours_day_time'), table_name='doctor_chamber_visiting_hours')
    op.add_column('doctors', sa.Column('image', sa.String(), nullable=True))
    op.drop_index(op.f('idx_doctors_name_trgm'), table_name='doctors', postgresql_ops={'full_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_doctors_search_vector'), table_name='doctors', postgresql_using='gin')
    op.drop_index(op.f('idx_doctors_specialization'), table_name='doctors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_doctors_specialization'), 'doctors', ['specialization'], unique=False)
    op.create_index(op.f('idx_doctors_search_vector'), 'doctors', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_doctors_name_trgm'), 'doctors', ['full_name'], unique=False, postgresql_ops={'full_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_column('doctors', 'image')
    op.create_index(op.f('idx_visiting_hours_day_time'), 'doctor_chamber_visiting_hours', ['day', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('idx_chambers_address_trgm'), 'chambers', ['address'], unique=False, postgresql_ops={'address': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
